config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  resources :movies
  resources :toys

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_attachment :photo
  has_many :toys
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  has_attachment :photo
  has_many :movies
  validates :rating, inclusion: { in: [0..10], allow_nil: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :address, :last_name, :phone_number]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :address, :last_name, :phone_number]
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to root_path
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    @movie.save
    redirect_to root_path
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :description, :release_date, :rating, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @movies = Movie.all
    @toys   = Toy.all
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all
  end

  def show
    @toy = Toy.find(params[:id])
  end

  def new
    @toy = Toy.new
  end

  def create
    @toy = Toy.new(toy_params)
    @toy.save
    redirect_to toys_path
  end

  private

  def toy_params
    params.require(:toy).permit(:name, :movie, :character, :price, :description, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pixar Toys</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/movies/edit.html.erb
<div class="container new_camera" >
  <h1> Edit a new movie </h1>
  <%= simple_form_for([@movie]) do |f| %>
    <%= f.input :name, collection: @names, include_blank: false %>
    <%= f.input :description %>
    <%= f.input :release_date, start_year: Date.today.year - 40, end_year: Date.today.year %>
    <%= f.input :rating %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/movies/new.html.erb
<div class="container" >
  <div class="text-control">
    <h1> Add a new movie </h1>
    <%= simple_form_for([@movie]) do |f| %>
      <%= f.input :name, collection: @names, include_blank: false %>
      <%= f.input :description %>
      <%= f.input :release_date, start_year: Date.today.year - 40, end_year: Date.today.year %>
      <%= f.input :rating %>
      <%= f.input :photo, as: :attachinary %>
      <%= f.button :submit, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="wrapper">
    <div class="container movie-poster">
        <div class="col-md-4">
            <% if @movie.photo? %>
              <%= cl_image_tag @movie.photo.path, width: 400, height: 500, crop: :fill %>
            <% end %>
        </div>
        <div class="col-md-4 col-md-offset-1">
            <div class="movie-info">
                <h1><%= @movie.name %></h1>
                <br>
                <p><strong>Description:</strong></p>
                <p><%= @movie.description %></p>
                <br>
                <p>Released on <%= @movie.release_date %></p>
                <p>IMDB Rating: <%= @movie.rating %>/10</p>
            </div>
        </div>
    </div>
</div>

app/views/pages/contact.html.erb
<h1>contact us</h1>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= asset_url 'banner.jpg' %>);">
  <div class="banner-content">
    <h1>Welcome to Pixar Toys</h1>
    <p>Very cool stuff, useful and smart</p>
    <div class="top">
      <a class="topArrow"><i class="fa fa-angle-down fa-inverse fa-5x" aria-hidden="true"></i></a>
    </div>
  </div>
</div>

<div class="bg-grey">
  <div class="container">
    <div class="row">
    <h1 class="text-center">Pixar movies</h1>
    <% @movies.each do |movie| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
      <% if movie.photo? %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path movie.photo.path %>);">
          <div class="card-category"><p><%= movie.rating %></p></div>
          <div class="card-description"><h2><%= movie.name %></h2></div>
          <a class="card-link" href="<%= movie_path(movie) %>" ></a>
        </div>
      <% else %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= asset_url 'cars.jpg' %>);">
          <div class="card-category"><p><%= movie.rating %></p></div>
          <div class="card-description"><h2><%= movie.name %></h2></div>
          <a class="card-link" href="<%= movie_path(movie) %>" ></a>
        </div>
      <% end %>
      </div>
    <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
  <h1 class="text-center">Popular Pixar Toys</h1>
  <% @toys.each do |toy| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
    <% if toy.photo? %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path toy.photo.path %>);">
        <div class="card-category"><p><%= toy.character %></p></div>
        <div class="card-description"><h2><%= toy.name %></h2></div>
        <a class="card-link" href="<%= toy_path(toy) %>" ></a>
      </div>
    <% else %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= asset_url 'cars.jpg' %>);">
        <div class="card-category"><p><%= toy.character %></p></div>
        <div class="card-description"><h2><%= toy.name %></h2></div>
        <a class="card-link" href="<%= toy_path(toy) %>" ></a>
      </div>
    <% end %>
    </div>
  <% end %>
  </div>
</div>

<div class="bg-grey">
  <div class="container text-left">
  <div class="home-content">
    <div class="row">
      <div class="col-md-4">
        <div class="img-home fadeIn">
          <%= image_tag 'clap.svg'%>
        </div>
      </div>
      <div class="col-md-6">
        <div class="content">
          <h3>Find cameras around you</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error sint ipsam optio, totam ad pariatur odio unde excepturi molestiae magnam quis dicta esse adipisci cum voluptatibus tempora tenetur eaque nam?</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error sint ipsam optio, totam ad pariatur odio unde excepturi molestiae magnam quis dicta esse adipisci cum voluptatibus tempora tenetur eaque nam?</p>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

  <div class="container text-left">
    <div class="home-content">
    <div class="row">
      <div class="col-md-6">
        <div class="content">
          <h3>Get the best choice</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error sint ipsam optio, totam ad pariatur odio unde excepturi molestiae magnam quis dicta esse adipisci cum voluptatibus tempora tenetur eaque nam?</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error sint ipsam optio, totam ad pariatur odio unde excepturi molestiae magnam quis dicta esse adipisci cum voluptatibus tempora tenetur eaque nam?</p>
        </div>
      </div>
      <div class="col-md-2 col-md-offset-2">
        <div class="img-home fadeIn">
          <%= image_tag 'focus.svg' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container text-center">
    <div class="row">
      <h4>Join Us On</h4>
    </div>
    <div class="row">
      <ul class="list-unstyled list-inline">
        <li><a href="http://www.facebook.com/toystorythree"><i class="fa fa-facebook" aria-hidden="true"></i></li></a>
        <li><a href=""><i class="fa fa-twitter" aria-hidden="true"></i></li></a>
        <li><a href=""><i class="fa fa-instagram" aria-hidden="true"></i></li></a>
        <li><a href=""><i class="fa fa-flickr" aria-hidden="true"></i></li></a>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "pixar-lamp.jpeg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
  </div>

  <!-- Dropdown list appearing on mobile only -->
    <% if user_signed_in? %>
      <% else %>
        <!-- Login text link -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>

  <div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/toys/new.html.erb
<div class="container new_toy" >
  <h1> Add a new toy </h1>
  <%= simple_form_for(@toy) do |f| %>
    <%= f.input :name, collection: @names, include_blank: false %>
    <%= f.input :movie %>
    <%= f.input :character %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/toys/show.html.erb
<h1><%= @toy.name %></h1>

<p>Descrition: <%= @toy.description %></p>
<p> <%= @toy.character %></p>
<p> <%= @toy.movie %></p>
<p>Price: <%= @toy.price %>$</p>

<% if @toy.photo? %>
  <%= cl_image_tag @toy.photo.path, width: 200, height: 300, crop: :fill %>
<% end %>